name: amsterdam
favicon: null
layout_spectrum: 0.74724
typography_spectrum: 0.62495
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b6b900'
    - '#7b008f'
    - '#00b7b3'
    - '#ffffff'
    - '#000000'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0
  rhythmicContrast: 1
purpose: []
