name: amsterdam
favicon: null
layout_spectrum: 0.5610489819664508
typography_spectrum: 0.8236264856532216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.23150977049954236
  lightness: 0.5451503084041178
  saturation: 0.3255106466822326
  rhythmicContrast: 0.0224201250821352
purpose: []
