name: amsterdam
favicon: null
layout_spectrum: 0.80608
typography_spectrum: 0.62495
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#251e14'
    - '#a2b5c4'
    - '#6f8fb6'
    - '#494431'
    - '#61634e'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
